# Generated by Django 5.2.6 on 2025-10-10 15:16

import ConferenceApp.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('conference_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('theme', models.CharField(choices=[('Computer Science & Artificial Intelligence', 'Computer Science & Artificial Intelligence'), ('Science & Engineering', 'Science & Engineering'), ('Social Sciences & Education', 'Social Sciences & Education'), ('Interdisciplinary Themes', 'Interdisciplinary Themes')], max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('ceated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('keywords', models.TextField(validators=[ConferenceApp.models.KeyWord_Validators])),
                ('paper', models.FileField(upload_to='papers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Only PDF and Word documents are allowed.')])),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=255)),
                ('payed', models.BooleanField(default=False)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_submissions', to='ConferenceApp.conference')),
            ],
        ),
    ]
